let strategyState=null,strategyTab='plan';
const metricLabels={views:'Visualizações',reach:'Alcance',likes:'Curtidas',comments:'Comentários',saved:'Salvamentos',shares:'Compartilhamentos',profile_visits:'Visitas ao perfil',follows:'Novos seguidores',retention:'Retenção (%)'};
async function strategy(){
 title('Estratégia de Conteúdo');$('#app').innerHTML='<div class="panel">Carregando estratégia…</div>';
 try{strategyState=await api('/strategy');drawStrategy()}catch(e){$('#app').innerHTML='<div class="panel warn">'+esc(e.message)+'</div>'}
}
function strategyCard(e){
 const s=e.strategy;
 return '<article class="strategy-card"><div class="meta"><span>'+esc(e.date)+' · Post '+(e.slot+1)+'</span><span class="pill">'+esc(s.theme)+'</span></div><h3>'+esc(e.title)+'</h3><p class="strategy-hook">'+esc(s.hook)+'</p><p><b>Público:</b> '+esc(s.audience)+'<br><b>Objetivo:</b> '+esc(s.objective)+'<br><b>Dor:</b> '+esc(s.pain)+'<br><b>Hipótese:</b> '+esc(s.hypothesis)+'<br><b>Métrica:</b> '+esc(metricLabels[s.primaryMetric])+'</p><p class="muted">Imagem: '+esc(s.visual.fileName)+'<br>Ângulo: '+esc(s.angle)+' · '+esc(s.format)+'</p><details><summary>Legenda completa</summary><p class="strategy-caption">'+esc(e.caption)+'</p></details><details><summary>Ideias de ganchos</summary><ul>'+s.hooks.map(h=>'<li>'+esc(h)+'</li>').join('')+'</ul></details><details><summary>Roteiro de Reel · 27 s</summary><p class="muted">Roteiro para produção. A fila publica a imagem; este roteiro não gera vídeo.</p><table><tbody>'+s.reel.map(r=>'<tr><td>'+esc(r.time)+'</td><td>'+esc(r.text)+'</td></tr>').join('')+'</tbody></table></details><div class="strategy-actions">'+(e.postId?'<button class="primary" data-strategy-action="queue">Abrir Aprovações</button>':'<button class="primary" data-strategy-action="draft" data-entry="'+esc(e.id)+'">Preparar imagem e agendar</button><button class="secondary" data-strategy-action="edit" data-entry="'+esc(e.id)+'">Editar</button><button class="secondary" data-strategy-action="regenerate" data-entry="'+esc(e.id)+'">Regenerar</button>')+'</div></article>';
}
function drawStrategy(){
 const d=strategyState,plan=d.plan,tabs=[['plan','Plano de 7 dias'],['ideas','Ideias e ganchos'],['reels','Reels'],['tests','Testes'],['results','Resultados'],['learning','Aprendizados']];
 $('#app').innerHTML='<section class="panel"><span class="k">ESTRATÉGIA ROVIX</span><h2>Conteúdo com propósito</h2><div class="note">'+esc(d.policy.rule)+'</div><form id="strategyGenerate" class="row"><label>Início da semana<input id="strategyDate" type="date" required></label><button class="primary">Gerar estratégia dos próximos 7 dias</button></form><p class="muted">Usa a quantidade e os horários da Automação. Preparar uma proposta cria um rascunho agendado, com prévia na fila de Aprovações.</p><div class="strategy-tabs">'+tabs.map(([key,label])=>'<button class="'+(strategyTab===key?'primary':'secondary')+'" data-strategy-tab="'+key+'">'+label+'</button>').join('')+'</div><div id="strategyBody"></div></section>';
 $('#strategyDate').value=plan?.startDate||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+86400000));
 $('#strategyGenerate').onsubmit=async ev=>{ev.preventDefault();const button=ev.target.querySelector('button');button.disabled=true;try{await api('/strategy/generate',{method:'POST',body:JSON.stringify({date:$('#strategyDate').value})});await strategy()}catch(e){alert(e.message)}finally{button.disabled=false}};
 document.querySelectorAll('[data-strategy-tab]').forEach(b=>b.onclick=()=>{strategyTab=b.dataset.strategyTab;drawStrategy()});
 const target=$('#strategyBody'),entries=plan?.entries||[];
 if(['plan','ideas','reels'].includes(strategyTab))target.innerHTML=entries.length?'<p class="muted">'+entries.length+' propostas · Plano criado em '+new Date(plan.createdAt).toLocaleString('pt-BR')+'</p><div class="strategy-grid">'+entries.map(strategyCard).join('')+'</div>':'<p>Gere o plano para visualizar as propostas.</p>';
 if(strategyTab==='tests')target.innerHTML='<p class="muted">Testes exploratórios de ganchos. Compare a mesma métrica considerando alcance e contexto; não são experimentos controlados.</p><div class="strategy-grid">'+entries.map(e=>'<article class="strategy-card"><b>'+esc(e.date)+' · '+esc(e.title)+'</b><p>Variável: '+esc(e.strategy.experiment.variable)+'<br>Variante: '+esc(e.strategy.experiment.variant)+'<br>Medida: '+esc(metricLabels[e.strategy.primaryMetric])+'</p><p>'+esc(e.strategy.hypothesis)+'</p></article>').join('')+'</div>';
 if(strategyTab==='learning')target.innerHTML='<p class="muted">Observações são usadas quando houver pelo menos duas publicações por variante comparável.</p>'+(d.learnings.length?d.learnings.map(l=>'<article class="strategy-card"><h3>'+esc(l.subject)+'</h3><p>'+esc(l.summary)+'</p><p>'+l.samples+' publicações com métrica e alcance.</p></article>').join(''):'<p>Aguardando resultados das primeiras publicações com estratégia.</p>');
 if(strategyTab==='results')target.innerHTML='<p class="muted">Os dados disponíveis são consultados no LinkedIn a cada 6 horas. Você também pode atualizar ou registrar métricas manualmente. Campos vazios significam indisponível. Retenção só se aplica a vídeo. As métricas gerais da conta continuam na Visão Geral.</p><button class="primary" id="strategyRefreshMetrics">Atualizar métricas do LinkedIn</button>'+(d.results.length?d.results.map(p=>'<article class="strategy-card"><h3>'+esc(p.title)+'</h3><p>Métrica principal: '+esc(metricLabels[p.strategy.primaryMetric])+'</p><p>'+Object.entries(p.performance?.metrics||{}).map(([k,v])=>esc(metricLabels[k])+': '+(v===null?'—':esc(v))).join(' · ')+'</p><button class="secondary" data-result="'+esc(p.id)+'">Registrar resultados</button></article>').join(''):'<p>Aguardando publicações com estratégia.</p>');
 document.querySelectorAll('[data-strategy-action]').forEach(b=>b.onclick=async()=>{const action=b.dataset.strategyAction;if(action==='queue')return view('queue');if(action==='edit')return editStrategy(b.dataset.entry);b.disabled=true;try{await api('/strategy/entries/'+encodeURIComponent(b.dataset.entry)+'/'+action,{method:'POST'});S.posts=await api('/posts');await strategy()}catch(e){alert(e.message)}finally{b.disabled=false}});
 if($('#strategyRefreshMetrics'))$('#strategyRefreshMetrics').onclick=async()=>{const b=$('#strategyRefreshMetrics');b.disabled=true;try{await api('/strategy/refresh-metrics',{method:'POST'});await strategy()}catch(e){alert(e.message)}finally{b.disabled=false}};
 document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>editResults(b.dataset.result));
}
function editStrategy(id){
 const e=strategyState.plan.entries.find(x=>x.id===id);
 $('#strategyBody').innerHTML='<form id="strategyEdit" class="grid"><label class="wide">Título<input id="strategyTitle" required></label><label class="wide">Gancho<input id="strategyHook" required></label><label class="wide">Hipótese<textarea id="strategyHypothesis" required></textarea></label><label class="wide">Legenda<textarea id="strategyCaption" rows="10" required></textarea></label><div><button class="primary">Salvar proposta</button> <button type="button" class="secondary" id="strategyCancel">Voltar</button></div></form>';
 $('#strategyTitle').value=e.title;$('#strategyHook').value=e.strategy.hook;$('#strategyHypothesis').value=e.strategy.hypothesis;$('#strategyCaption').value=e.caption;$('#strategyCancel').onclick=drawStrategy;
 $('#strategyEdit').onsubmit=async ev=>{ev.preventDefault();try{await api('/strategy/entries/'+encodeURIComponent(id)+'/edit',{method:'POST',body:JSON.stringify({title:$('#strategyTitle').value,hook:$('#strategyHook').value,hypothesis:$('#strategyHypothesis').value,caption:$('#strategyCaption').value})});await strategy()}catch(err){alert(err.message)}};
}
function editResults(id){
 const p=strategyState.results.find(x=>x.id===id);
 $('#strategyBody').innerHTML='<h3>'+esc(p.title)+'</h3><form id="strategyMetrics" class="grid">'+Object.entries(metricLabels).map(([key,label])=>'<label>'+label+'<input type="number" min="0" '+(key==='retention'?'max="100" step="0.1"':'step="1"')+' data-metric="'+key+'" value="'+esc(p.performance?.metrics?.[key]??'')+'"></label>').join('')+'<div><button class="primary">Salvar métricas</button> <button type="button" class="secondary" id="strategyCancel">Voltar</button></div></form>';$('#strategyCancel').onclick=drawStrategy;
 $('#strategyMetrics').onsubmit=async ev=>{ev.preventDefault();const values={};document.querySelectorAll('[data-metric]').forEach(x=>values[x.dataset.metric]=x.value===''?null:Number(x.value));try{await api('/strategy/posts/'+encodeURIComponent(id)+'/metrics',{method:'PUT',body:JSON.stringify(values)});await strategy()}catch(e){alert(e.message)}};
}
