const CONFIG = window.ROVIX_HUB_CONFIG;
const $ = id => document.getElementById(id);
const loginScreen=$('loginScreen'), hubScreen=$('hubScreen'), loginForm=$('loginForm'), loginMessage=$('loginMessage'), logoutButton=$('logoutButton'), welcomeText=$('welcomeText'), systemsContainer=$('systemsContainer'), apiDot=$('apiDot'), apiStatusTitle=$('apiStatusTitle'), apiStatusText=$('apiStatusText');
const getToken=()=>localStorage.getItem(CONFIG.STORAGE_KEYS.authToken);
function getUser(){try{return JSON.parse(localStorage.getItem(CONFIG.STORAGE_KEYS.authUser)||'null')}catch{return null}}
function saveSession(data,username){const token=data?.access_token||data?.token||data?.accessToken||data?.jwt;if(!token)throw new Error('Token não recebido.');localStorage.setItem(CONFIG.STORAGE_KEYS.authToken,token);localStorage.setItem(CONFIG.STORAGE_KEYS.authUser,JSON.stringify({username,name:data?.user?.name||data?.user?.username||username,savedAt:new Date().toISOString()}));}
function clearSession(){localStorage.removeItem(CONFIG.STORAGE_KEYS.authToken);localStorage.removeItem(CONFIG.STORAGE_KEYS.authUser)}
function showLogin(message=''){loginScreen.classList.remove('hidden');hubScreen.classList.add('hidden');logoutButton.classList.add('hidden');loginMessage.textContent=message}
function showHub(){loginScreen.classList.add('hidden');hubScreen.classList.remove('hidden');logoutButton.classList.remove('hidden');const u=getUser();welcomeText.textContent=`Bem-vindo, ${u?.name||u?.username||'Roberto'}. Todos os sistemas da Rovix em um só lugar.`;renderSystems();checkApiHealth();updateClock();}
function renderSystems(){systemsContainer.innerHTML='';let count=0;CONFIG.SYSTEMS.forEach(group=>{const section=document.createElement('section');section.className='system-group';section.innerHTML=`<div class="group-title"><div class="group-icon">${group.icon}</div><div><h3>${group.group}</h3><p>${group.subtitle||''}</p></div></div>`;const grid=document.createElement('div');grid.className='system-grid';group.items.forEach(item=>{if(!item.disabled)count++;const card=document.createElement('article');card.className=`system-card glass ${item.disabled?'disabled':''} ${item.featured?'featured':''}`;card.innerHTML=`<div class="card-top"><span class="app-icon">${item.icon||group.icon}</span><span class="badge">${item.badge}</span></div><h4>${item.name}</h4><p>${item.description}</p><a class="system-button" href="${item.disabled?'#':item.url}" ${item.disabled?'aria-disabled="true"':'target="_blank" rel="noopener"'}>${item.disabled?'Em breve':'Abrir sistema'}<span>→</span></a>`;grid.appendChild(card)});section.appendChild(grid);systemsContainer.appendChild(section)});$('systemCount').textContent=count;}
async function login(username,password){const url=`${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.login}`;let lastError;for(const body of [{username,password},{email:username,password},{login:username,password}]){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(r.ok){saveSession(d,username);return}lastError=d?.detail||d?.message||`Erro ${r.status}`}catch(e){lastError=e.message}}throw new Error(lastError||'Falha no login')}
async function checkApiHealth(){apiDot.className='dot checking';try{const r=await fetch(`${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.health}`,{cache:'no-store'});if(!r.ok)throw 0;apiDot.className='dot online';apiStatusTitle.textContent='TAG API Online';apiStatusText.textContent='Backend respondendo normalmente.'}catch{apiDot.className='dot offline';apiStatusTitle.textContent='TAG API indisponível';apiStatusText.textContent='Os atalhos continuam disponíveis.'}}
function updateClock(){const now=new Date();$('currentTime').textContent=now.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('currentDate').textContent=now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});}
setInterval(updateClock,30000);
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginMessage.textContent='Autenticando...';const f=new FormData(loginForm);try{await login(String(f.get('username')||'').trim(),String(f.get('password')||''));loginForm.reset();showHub()}catch(err){loginMessage.textContent='Não foi possível entrar. Confira usuário e senha.';console.error(err)}});
logoutButton.addEventListener('click',()=>{clearSession();showLogin('Sessão encerrada.')});
getToken()?showHub():showLogin();
