import test from 'node:test';
import assert from 'node:assert/strict';
import {linkedInConfigured,testLinkedIn,publishLinkedIn} from './linkedin-publisher.mjs';
const originalFetch=globalThis.fetch;
const initial={...process.env};
test.afterEach(()=>{globalThis.fetch=originalFetch;for(const k of Object.keys(process.env))if(!(k in initial))delete process.env[k];Object.assign(process.env,initial)});
function configure(){process.env.LINKEDIN_ACCESS_TOKEN='test-token';process.env.LINKEDIN_AUTHOR_URN='urn:li:person:example'}
test('rejects missing credentials and overlong commentary before network',async()=>{delete process.env.LINKEDIN_ACCESS_TOKEN;globalThis.fetch=()=>assert.fail('network should not be called');assert.equal(linkedInConfigured(),false);await assert.rejects(publishLinkedIn({caption:'Teste'}),/configurada/);configure();await assert.rejects(publishLinkedIn({caption:'a'.repeat(3001)}),/3000/)});
test('text publication uses author and LinkedIn response header',async()=>{configure();let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://api.linkedin.com/rest/posts');const data=JSON.parse(options.body);assert.equal(data.author,'urn:li:person:example');assert.equal(data.commentary,'Texto');assert.equal(data.content,undefined);return new Response('',{status:201,headers:{'x-restli-id':'urn:li:share:123'}})};const result=await publishLinkedIn({caption:'Texto'});assert.equal(result.id,'urn:li:share:123');assert.equal(calls,1)});
test('uploads complete image then attaches returned image URN',async()=>{configure();process.env.LINKEDIN_IMAGE_ALLOWED_HOSTS='images.example.com';const calls=[];globalThis.fetch=async(url,options={})=>{calls.push(url);if(url==='https://images.example.com/final.jpg')return new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'image/jpeg'}});if(url.includes('initializeUpload'))return Response.json({value:{uploadUrl:'https://www.linkedin.com/dms-uploads/test',image:'urn:li:image:abc'}});if(url.includes('/dms-uploads/')){assert.equal(options.method,'PUT');assert.deepEqual([...options.body],[1,2,3]);return new Response('',{status:201})}const data=JSON.parse(options.body);assert.equal(data.content.media.id,'urn:li:image:abc');return new Response('',{status:201,headers:{'x-restli-id':'urn:li:share:456'}})};assert.equal((await publishLinkedIn({caption:'Post com imagem',title:'Produto'},'https://images.example.com/final.jpg')).id,'urn:li:share:456');assert.equal(calls.length,4)});
test('uncertain publish failure is never retried',async()=>{configure();let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('timeout')};await assert.rejects(publishLinkedIn({caption:'Teste'}),/timeout/);assert.equal(calls,1)});
test('rejects untrusted images and mismatch between profile token and configured author',async()=>{configure();globalThis.fetch=()=>assert.fail('untrusted image must not be fetched');await assert.rejects(publishLinkedIn({caption:'Teste'},'http://127.0.0.1/image.jpg'),/acervo autorizado/);globalThis.fetch=async()=>Response.json({sub:'different'});await assert.rejects(testLinkedIn(),/não corresponde/)});
