import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {sealConnection,openConnection,validAdmin,handleLinkedInConnection} from './linkedin-connection.mjs';
const initial={...process.env};const oldFetch=globalThis.fetch;
test.afterEach(()=>{globalThis.fetch=oldFetch;for(const k of Object.keys(process.env))if(!(k in initial))delete process.env[k];Object.assign(process.env,initial)});
function response(){return {status:null,headers:{},body:'',setHeader(k,v){this.headers[k]=v},writeHead(code,headers){this.status=code;Object.assign(this.headers,headers)},end(body=''){this.body=body}}}
function session(){process.env.LINKEDIN_ROVIX_SESSION_SECRET='test-session-secret';const payload='admin|'+(Date.now()+60000);const signature=crypto.createHmac('sha256',process.env.LINKEDIN_ROVIX_SESSION_SECRET).update(payload).digest('hex');return Buffer.from(payload+'|'+signature).toString('base64url')}
test('connection is encrypted and tampering fails authentication',()=>{process.env.LINKEDIN_OAUTH_SECRET='x'.repeat(64);const data={accessToken:'secret-token',author:'urn:li:person:test'};const sealed=sealConnection(data);assert.ok(!JSON.stringify(sealed).includes('secret-token'));assert.deepEqual(openConnection(sealed),data);sealed.tag=Buffer.alloc(16).toString('base64');assert.throws(()=>openConnection(sealed))});
test('OAuth start requires authenticated agent session',async()=>{const res=response();await handleLinkedInConnection({url:'/linkedin/oauth/connect',method:'GET',headers:{}},res);assert.equal(res.status,401)});
test('OAuth URL requests publishing scope and signed state',async()=>{process.env.LINKEDIN_CLIENT_ID='test-client';process.env.LINKEDIN_CLIENT_SECRET='test-secret';process.env.LINKEDIN_OAUTH_SECRET='x'.repeat(64);const token=session();assert.ok(validAdmin({headers:{authorization:'Bearer '+token}}));const res=response();await handleLinkedInConnection({url:'/linkedin/oauth/connect',method:'GET',headers:{authorization:'Bearer '+token}},res);assert.equal(res.status,302);const u=new URL(res.headers.Location);assert.equal(u.hostname,'www.linkedin.com');assert.ok(u.searchParams.get('scope').includes('w_member_social'));assert.ok(res.headers['Set-Cookie'].includes('HttpOnly'));assert.ok(!res.headers.Location.includes('test-secret'))});
test('callback with forged state is rejected before token exchange',async()=>{process.env.LINKEDIN_OAUTH_SECRET='x'.repeat(64);globalThis.fetch=()=>assert.fail('no token exchange for forged state');const res=response();await handleLinkedInConnection({url:'/linkedin/oauth/callback?state=forged&code=test',method:'GET',headers:{cookie:'linkedin_oauth_state=forged'}},res);assert.equal(res.status,400)});
