import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, LockKeyhole } from "lucide-react";
import "../../orpheus/portal.css";
export const metadata:Metadata={title:"Dossiê 00 — Antes de ORPHEUS | CIPHER",description:"Arquivo classificado suplementar do universo CIPHER — Protocolo Orpheus.",robots:{index:false,follow:false}};
export default function Dossie00(){return <div className="cipherPortal"><main className="d00">
<section className="d00Hero"><div className="shell"><p className="section-index">CIPHER // DOSSIÊ 00 // ACESSO NÍVEL 01</p><h1>ANTES DE<br/><em>ORPHEUS</em></h1><p className="lede">Você recebeu acesso a um arquivo que não faz parte do registro público.</p><div className="red-stamp"><LockKeyhole size={16}/> ARQUIVO CLASSIFICADO</div></div></section>
<section className="section"><div className="shell d00Grid"><div><p className="section-index">REGISTRO // 00.1</p><h2>O silêncio veio primeiro.</h2></div><div><p>Há operações que terminam no papel. Outras apenas desaparecem dos registros. Quando um nome volta a circular depois de anos de silêncio, a primeira pergunta não é quem o encontrou. É quem nunca deixou de procurar.</p><p>O sujeito associado a este arquivo atende pelo nome de <strong>Blake Langmere</strong>. Ex-militar, servidor público e especialista em segurança cibernética. A vida atual foi construída para parecer comum. O problema é que o passado não respeita arquitetura.</p><pre>&gt; QUERY: BLAKE_LANGMERE{"\n"}&gt; RESULT: PARTIAL MATCH{"\n"}&gt; HISTORICAL RECORD: FRAGMENTED{"\n"}&gt; TRACE: ACTIVE</pre></div></div></section>
<section className="section d00Dark"><div className="shell d00Grid"><div><p className="section-index">INTERCEPTAÇÃO // 00.2</p><h2>A caixa.</h2></div><div><p>O primeiro elemento relevante não é digital. Não é uma senha, um servidor ou uma transmissão. É uma caixa. Um objeto banal o suficiente para atravessar anos sem chamar atenção — e perigoso o bastante para alterar tudo quando finalmente é aberto.</p><blockquote>A pergunta não é quem encontrou Blake. É por que esperaram tanto tempo.</blockquote></div></div></section>
<section className="section"><div className="shell"><p className="section-index">MAPA DE RISCO // 00.3</p><h2>Quatro nomes. Nenhuma leitura simples.</h2><div className="d00Cards"><article><b>BLAKE LANGMERE</b><p>O passado que ele enterrou acaba de ser encontrado.</p></article><article><b>LARA LANGMERE</b><p>Ela conhece Blake melhor do que qualquer arquivo.</p></article><article><b>EVELYN CROSS</b><p>Cada detalhe é uma pista. Cada silêncio, uma escolha.</p></article><article><b>GORDON SULLIVAN</b><p>Um aliado estratégico com acesso parcial ao protocolo.</p></article></div></div></section>
<section className="section d00End"><div className="shell"><p className="section-index">PROTOCOLO // 00.4</p><h2>Este arquivo não contém a resposta.<br/>Ele contém a porta.</h2><p>Alguns registros só fazem sentido depois da última página. A investigação começa em <strong>CIPHER — Protocolo Orpheus</strong>.</p><div className="hero-actions"><Link className="button-primary" href="/cipher/#comprar">ACESSAR O LIVRO <ArrowRight size={17}/></Link><Link className="button-quiet" href="/cipher/"><ArrowLeft size={16}/> VOLTAR AO CIPHER</Link></div></div></section>
</main></div>}